### ISSUE TITLE
关于查到的性格

### ISSUE THREAD

**Issue by coroler** [wwwwwwzx/raidtool#1]
性格项好像部分与查询结果不一致。我尝试抓了一只，根据计算结果是乐天，但实际抓到的性格锁了固执。

**Comment by wwwwwwzx** [comment]
1）是固定性别的吗
2）是毒电吗

**Comment by coroler** [comment]
1）性别没注意，下次有机会找别人看隐藏参数的时候再看看
2）是拉普拉斯，中间抓了一次雪童子，一次冰鬼护也都是固执

**Comment by wwwwwwzx** [comment]
把seed发一下

**Comment by coroler** [comment]
PID = 0x475C35D4
EC = 0xA36399A5
IVs = [6, 22, 23, 31, 15, 31]

第263帧的结果

**Comment by wwwwwwzx** [comment]
没问题
https://github.com/wwwwwwzx/raidtool/blob/master/raidtool.py#L36
RandomGender 改成 1
